### ISSUE TITLE
FileZilla related issues

### ISSUE THREAD

**Issue by omnignorant** [PermanentOrg/sftp-service#94] opened 2023-03-01 22:21 UTC
I have encountered a few issues when using FileZilla but they seem to be due to this error:
```
Error:         	FATAL ERROR: Connection reset by peer
```
Every time this happens, file transfers are interrupted. Sometimes this cause them to 

- fail outright
- resume and complete successfully
- create duplicates

I believe the outcome depends on when the transfer is interrupted.

Moreover, FileZilla must be run in "interactive mode" when 2FA is turned on. That means every time there is a reconnection required, the user must enter their password, select a 2FA option, and enter the 2FA code.

However, and this has been hard to determine given the disconnection errors, it may also be the case that the password/2FA must be entered for every SFTP command executed in FileZilla. Unclear.

Also a fact that even in normal mode, where the password is stored in FileZilla and the user is not prompted, the user is sometimes prompted.

Maybe FileZilla is the problem? I will try another client.

https://user-images.githubusercontent.com/6335874/222276303-2d5ab664-3468-478d-b447-df0b9ab1da02.mov

**Comment by omnignorant** [comment] 2023-03-01 22:24
also got this error:
```Error:         	FATAL ERROR: Remote side unexpectedly closed network connection```

**Comment by slifty** [comment] 2023-03-02 15:50
There may be a few things going on here:

1. Incorrect filenames are being generated when extensions are capitalized (e.g. `.JPG`).  See #95  -- this can result in odd behavior since from filezilla's perspective the file doesn't end up as "uploaded" (e.g. the file doesn't end up existing in the spot it expects) 

2. I think that if the client tries to read a newly created file before it has been processed, there is a potential since the size has not yet been assigned. (this is basically the same as a concern that Robert raised in slack).  This is resulting in an attempt to "download" a URL that doesn't yet exist which in turn results in an error from `fetch`.

Both of these could result in strange behavior, but I think most of the errors you're facing here are rooted in the second.

sftp service returns a `failure` status code in the event of the second situation, which filezilla *might* be reacting to by closing the connection.  I'm going to find a more specific status code to return and it might improve the situation.  Beyond that, though, we have a deeper quandary related to the fact that files have to be processed in order to be considered truly "uploaded" -- and we may or may not want that processing to block sftp.

**Comment by slifty** [comment] 2023-03-02 20:47
I don't want to blow away the filezilla context so I'm keeping this open, but also creating a new issue to capture the processing timing question.

**Comment by slifty** [comment] 2023-04-07 14:32
A lot of fixes have been made which address what I believe were the root causes of these bugs.  I'm closing, and future filezilla issues should probably result in a new issue.

**Closed by slifty** 2023-04-07 14:32 UTC
